
copyright: Fincz
title: "How to Start Investing in Stocks"
email: contact@theisalh.com
timezone: IST
baseurl: "/fincz"
permalink: "/:title/"
logo: 'assets/images/fincz-logo-black.png'
favicon: 'assets/images/apple-icon-black.png'
author: Ahmad
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  Ahmad:
    name: Ahmad
    display_name: Ahmad
    avatar: 'assets/images/Ahmad.png'
    email: itechf@hotmail.com
    web: https://itechf.com
    twitter: https://twitter.com/itechf2
    description: "Author of FinCz a website for share market"
  Nazir:
    name: Nazir
    display_name: Nazir
    avatar: 'assets/images/Nazir.png'
    email: nazir@gmail.com
    web: https://bestrani.com
    twitter: https://twitter.com/bestrani3
    description: "Nazir has so much experience of content writing"

# Social
social:
  instagram: https://www.instagram.com/fincz/
  facebook: https://www.facebook.com/fincz
  twitter: https://twitter.com/fincz

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives